from datetime import datetime, timezone
from typing import Optional, List, Literal
from pydantic import BaseModel, Field, ConfigDict, AfterValidator, AwareDatetime
from decimal import Decimal
from typing import Annotated

Money = Annotated[Decimal, Field(max_digits=14, decimal_places=2, allow_inf_nan=False)]
PositiveMoney = Annotated[Money, Field(gt=0, le=Decimal("999999999999.99"))]


def persisted_utc(value: datetime) -> datetime:
    """Restore UTC stripped by SQLite; aware database values normalize to UTC."""
    return (
        value.replace(tzinfo=timezone.utc)
        if value.tzinfo is None
        else value.astimezone(timezone.utc)
    )


UTCResponse = Annotated[datetime, AfterValidator(persisted_utc)]
UTCInput = Annotated[AwareDatetime, AfterValidator(lambda value: value.astimezone(timezone.utc))]


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


# --- Account Schemas ---
class AccountBase(StrictModel):
    name: str = Field(min_length=1, max_length=100)
    group_name: str = "Личное"
    bank_name: Optional[str] = None
    balance: Money = Decimal("0.00")
    currency: str = Field(default="RUB", pattern="^[A-Z]{3}$")
    icon: str = "💳"
    color: str = "#2B5BFF"
    is_default: bool = False
    sort_order: int = 0


class AccountCreate(AccountBase):
    pass


class AccountUpdate(StrictModel):
    name: Optional[str] = None
    group_name: Optional[str] = None
    bank_name: Optional[str] = None
    icon: Optional[str] = None
    color: Optional[str] = None
    is_default: Optional[bool] = None


class AccountResponse(AccountBase):
    balance: float
    is_archived: bool = False
    id: str
    user_id: int
    created_at: UTCResponse
    model_config = ConfigDict(from_attributes=True)


# --- Category Schemas ---
class CategoryBase(StrictModel):
    name: str = Field(min_length=1, max_length=100)
    type: Literal["expense", "income", "both"] = "expense"
    icon: str = "📦"
    color: str = "#F3F4F6"
    budget_limit: Optional[Money] = None
    sort_order: int = 0

    parent_id: Optional[str] = None


class CategoryCreate(CategoryBase):
    pass


class CategoryUpdate(StrictModel):
    name: Optional[str] = Field(default=None, min_length=1, max_length=100)
    type: Optional[Literal["expense", "income", "both"]] = None
    icon: Optional[str] = None
    color: Optional[str] = None
    parent_id: Optional[str] = None
    budget_limit: Optional[Money] = None
    sort_order: Optional[int] = None


class CategoryResponse(CategoryBase):
    budget_limit: Optional[float] = None
    is_archived: bool = False
    id: str
    user_id: int
    created_at: UTCResponse
    model_config = ConfigDict(from_attributes=True)


# --- Transaction Schemas ---
class TransactionCreate(StrictModel):
    account_id: str
    to_account_id: Optional[str] = None
    category_id: Optional[str] = None
    amount: PositiveMoney
    type: Literal["expense", "income", "transfer"] = "expense"
    note: Optional[str] = Field(default=None, max_length=2000)
    created_at: Optional[UTCInput] = None
    client_id: Optional[str] = Field(
        default=None, min_length=1, max_length=64
    )  # Idempotency key generated by frontend


class TransactionUpdate(StrictModel):
    revision: int = Field(ge=1)
    account_id: Optional[str] = None
    to_account_id: Optional[str] = None
    category_id: Optional[str] = None
    amount: Optional[PositiveMoney] = None
    type: Optional[Literal["expense", "income", "transfer"]] = None
    note: Optional[str] = Field(default=None, max_length=2000)
    created_at: Optional[UTCInput] = None


class TransactionResponse(BaseModel):
    revision: int
    currency: Optional[str] = None
    id: str
    user_id: int
    account_id: str
    to_account_id: Optional[str] = None
    category_id: Optional[str] = None
    amount: float
    type: str
    note: Optional[str] = Field(default=None, max_length=2000)
    created_at: UTCResponse

    # Nested preview fields
    account_name: Optional[str] = None
    category_name: Optional[str] = None
    category_icon: Optional[str] = None

    model_config = ConfigDict(from_attributes=True)


# --- AI Parsing Schemas ---
class AIParsedTransaction(BaseModel):
    amount: PositiveMoney = Field(description="Сумма операции")
    type: Literal["expense", "income", "transfer"] = Field(
        default="expense", description="Тип операции: расход, доход или перевод"
    )
    category_name: Optional[str] = Field(
        default=None, description="Название категории, например: Еда, Транспорт, Покупки, Здоровье"
    )
    account_name: Optional[str] = Field(
        default=None, description="Название счета списания, например: Карта Альфа, Т-Банк, Наличные"
    )
    to_account_name: Optional[str] = Field(
        default=None, description="Название счета зачисления (для перевода)"
    )
    note: Optional[str] = Field(
        default=None,
        description="Краткое описание или комментарий, например: Кофе, Такси, Продукты",
    )


class PendingClarification(BaseModel):
    question: str
    suggested_amount: Optional[float] = None
    suggested_options: List[float] = Field(default_factory=list)
    type: str = "expense"
    category_name: Optional[str] = None
    account_name: Optional[str] = None
    note: Optional[str] = Field(default=None, max_length=2000)


class AIParsedResult(BaseModel):
    transactions: List[AIParsedTransaction] = Field(
        default_factory=list, description="Список распознанных транзакций"
    )
    clarification: Optional[str] = Field(
        default=None, description="Если что-то не понятно или не хватает данных"
    )
    pending: Optional[PendingClarification] = Field(
        default=None, description="Запрос на уточнение суммы или деталей"
    )


# --- Dashboard & Analytics Schemas ---
class CategoryStat(BaseModel):
    id: str
    name: str = Field(min_length=1, max_length=100)
    icon: str
    color: str
    total_amount: float
    percentage: float


class DashboardSummary(BaseModel):
    currency: str = "RUB"
    balances_by_currency: dict[str, float] = Field(default_factory=dict)
    totals_by_currency: dict[str, dict[str, float]] = Field(default_factory=dict)
    total_balance: float
    period_label: str
    period_income: float
    period_expense: float
    categories: List[CategoryStat]
    recent_transactions: List[TransactionResponse]
